sudo: false
language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3.3
  - 2.4.0
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: jruby-head
before_install: gem install bundler
script:
  - ci/test
